### ISSUE TITLE
warpctc error: AttributeError: 'module' object has no attribute 'WarpCTC'

### ISSUE THREAD

**Issue by qieaaa** [xlvector/learning-dl#12]
hello , I tried to run you code about LSTM-CTC, but warpctc doesnt work well .I wonder if you met this problem when run the mxnet with warpctc,I'm looking forward for you help.Here is what I did:
1. I installed mxnet , warp-ctc respectively, totally follow the official guide. Then I run tests. each of them works well.

2. I enabled warpctc in mxnet ,commented out following lines in mxnet/config.mk
WARPCTC_PATH = $(HOME)/warp-ctc
MXNET_PLUGINS += plugin/warpctc/warpctc.mk
rebuilt mxnet after that.

3. then I get the following results,last line shows:
make[1]: Leaving directory `/home/lab/mxnet/dmlc-core'
then the make process stopped. I found mxnet still works,but there are no bin and lib files in mxnet. when I run the lstm_ocr demo,it shows:
Traceback (most recent call last):
File "lstm_ocr.py", line 157, in 
symbol = sym_gen(SEQ_LENGTH)
File "lstm_ocr.py", line 148, in sym_gen
num_label = num_label)
File "/home/lab/mxnet/example/warpctc/lstm.py", line 77, in lstm_unroll
sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)
AttributeError: 'module' object has no attribute 'WarpCTC'

**Comment by lionel92** [comment]
Have you solved this problem? I met the same problem with you.
