### ISSUE TITLE
I can't run the infer_cnn_ocr.py

### ISSUE THREAD

**Issue by szad670401** [xlvector/learning-dl#5]
I trained the ocr model follow the can_ocr.py
but when i run infer_cnn_ocr.py it occurs a error:

Traceback (most recent call last):
  File "/Users/yujinke/learning cpp/untitled5/ete.py", line 75, in <module>
    TestRecognizeOne(cv2.imread("./plate/31/00.jpg"))
  File "/Users/yujinke/learning cpp/untitled5/ete.py", line 56, in TestRecognizeOne
    executor = sym.simple_bind(ctx = mx.cpu(), **input_shapes)
  File "/Library/Python/2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 675, in simple_bind
    raise ValueError("Input node is not complete")
ValueError: Input node is not complete

**Comment by szad670401** [comment]
I have fixed the problem.

**Comment by xlvector** [comment]
Because you used old mxnet?

**Comment by szad670401** [comment]
I make some changes on you code, I thought the get_ocrnet() function is same in two files.

**Comment by xlvector** [comment]
Thanks, you can submit a PR
